export const industries = [
  {
    category: 'Beauty and Personal Care',
    specifics: [
      'Health and beauty',
      'Massage parlours',
      'Salons and barbers',
      'Tattoo and piercings',
      'Other',
    ],
  },
  {
    category: 'Building, home and repair',
    specifics: [
      'Auto repairs',
      'Builders',
      'Building supplies',
      'Carpenters',
      'Cleaning',
      'Dry cleaning and Laundry',
      'Electrical repairs',
      'Electricians',
      'Gardening',
      'Landscaping',
      'Painting and decorating',
      'Plumbers',
      'Removals',
      'Telecom equipments',
      'Telecom services',
      'Other',
    ],
  },
  {
    category: 'Digital Products',
    specifics: [
      'Apps',
      'Blogs and written content',
      'Books',
      'Games',
      'Music',
      'Software as a service',
      'Video and film',
      'Other',
    ],
  },
  {
    category: 'Education',
    specifics: [
      'Childcare services',
      'Schools and universities',
      'Tutoring / instructing',
      'Vocational / apprenticeships',
      'Other',
    ],
  },
  {
    category: 'Entertainment and recreation',
    specifics: [
      'Bands, musicians, orchestras',
      'Betting and fantasy sport',
      'Cinemas',
      'Events and festivals',
      'Gambling',
      'Lotteries',
      'Sporting events',
      'Ticketing',
      'Tourist attractions',
      'Other',
    ],
  },
  {
    category: 'Financial Services',
    specifics: [
      'Banking',
      'Cryptocurrencies',
      'Currency exchange',
      'Digital wallets',
      'Insurance',
      'Investment services',
      'Loans and lending',
      'Payments',
      'Security brokers or dealers',
      'Virtual currencies',
      'Other',
    ],
  },
  {
    category: 'Food and drink',
    specifics: [
      'Cafes',
      'Catering',
      'Food stand / vendors',
      'Grocery stores',
      'Pubs / Bars / Clubs',
      'Restaurants',
      'Wholesalers',
      'Other',
    ],
  },
  {
    category: 'Healthcare and fitness',
    specifics: [
      'Gym / health club',
      'Personal training',
      'Physiotherapy and sports massage',
      'Other',
    ],
  },
  {
    category: 'Medical and mental health',
    specifics: [
      'Assisted living',
      'Chiropractors',
      'Dentists and orthodontists',
      'Doctors',
      'Hospitals',
      'Medical devices',
      'Mental health services',
      'Nursing',
      'Opticians or eye care',
      'Telemedicine and Telehealth',
      'Therapy and counselling',
      'Veterinary services',
      'Other',
    ],
  },
  {
    category: 'Membership Organisations',
    specifics: [
      'Charities or social organisations',
      'Political Organisations',
      'Religious organisations',
      'Sports clubs',
      'Other',
    ],
  },
  {
    category: 'Professional Services',
    specifics: [
      'Accounting',
      'Auto services',
      'Car rentals',
      'Car sales',
      'Computer repair',
      'Consulting',
      'Design',
      'Estate agency',
      'Government services',
      'Lead generation',
      'Legal services',
      'Marketing',
      'Photography',
      'Printing and publishing',
      'Software development',
      'Utilities',
      'Other',
    ],
  },
  {
    category: 'Regulated and age-restricted',
    specifics: [
      'Adult content or services',
      'Alcohol',
      'Dating',
      'e-cigarettes, vaping and related products',
      'Gambling',
      'Pharmaceuticals',
      'Supplements',
      'Tobacco, cigars, cigarettes',
      'Other',
    ],
  },
  {
    category: 'Retail',
    specifics: [
      'Auto parts and accessories',
      'Beauty Products',
      'Car sales',
      'Clothing and accessories',
      'Computing',
      'Home electronics',
      'Home goods and furniture',
      'Jewellery and Watches',
      'Newsagents',
      'Pets',
      'Precious stones, metals, watches and Jewellery',
      'Software',
      'Sporting',
      'Supermarkets',
      'Wholesalers',
      'Other ',
    ],
  },
  {
    category: 'Transportation',
    specifics: [
      'Airlines',
      'Commuter transport',
      'Courier and delivery services',
      'Parking',
      'Removals',
      'Ridesharing',
      'Shipping',
      'Taxis',
      'Travel agencies',
      'Other',
    ],
  },
  {
    category: 'Travel and accommodation',
    specifics: ['Hotels, inns and B&Bs', 'Property rentals', 'Other'],
  },
];
