export enum ROUTES {
  HOME = '/',
  LOGIN = '/login',
  SIGN_UP = '/register',
  SIGN_UP_ADDITIONAL = '/register/additional',
  SIGN_UP_BUSINESS = '/register/business',
  PRODUCT = '/product',
  CONNECT = '/connect',
  REPROT = '/report',
  DASHBOARD = '/dashboard',
  TRANSACTION = '/transactions',
  MERCHANTS = '/merchants',
  PAYMENT = '/dashboard/payment',
  PAYMENT_INVOICE = '/dashboard/payment/invoice',
  // PAYMENT_INVOICE_PREVIEW = '/dashboard/payment/invoice/preview',
  PAYMENT_INVOICE_CREATE = '/dashboard/payment/invoice/create',
  PAYMENT_RECURRING = '/dashboard/payment/recurring',
  PAYMENT_QUOTES = '/dashboard/payment/quotes',
  PAYMENT_PAY_BY_LINK = '/dashboard/payment/link',
  PAYMENT_PAY_BY_QR = '/dashboard/payment/qr',
  PAYMENT_QR_CREATE = '/dashboard/payment/qr/create',
  PAYMENT_LINK_CREATE = '/dashboard/payment/link/create',
  MANAGE_BANK_ACCOUNT = '/dashboard/settings/bank-account',
  CREATE_BANK_ACCOUNT = '/dashboard/settings/bank-account/create',
  BUSINESS_DETAILS = '/dashboard/settings/business-details',
  MANAGE_INTEGRATIONS = '/dashboard/settings/integrations',
  MANAGE_TERMINAL = '/dashboard/settings/terminal',
  TERMINAL_SETTINGS = '/dashboard/settings/terminal',
  CREATE_TERMINAL = '/dashboard/settings/terminal/create',
  
}
